# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 08:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='')),
                ('title', models.CharField(default=0, max_length=50)),
                ('artist', models.CharField(default='Vinit', max_length=100)),
                ('genre', models.CharField(default='Rock', max_length=30)),
                ('details', models.TextField(default=0, max_length=200)),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
