# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='title',
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.CharField(default='Vinit', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='details',
            field=models.TextField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(default='Rock', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='tilte',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='logo',
            field=models.FileField(upload_to=''),
        ),
    ]
